///////////////////////////////////////////////////////////////////////
// Class:       SignalPionAbsorption
// Module Type: filter
// File:        SignalPionAbsorption_module.cc
//
// Created on December 2024 by Emilio Peláez
//
// This filter checks if the particle interaction is a pion absorption
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDFilter.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "LArIATDataProducts/WCTrack.h"
#include "canvas/Persistency/Common/FindOneP.h" 
#include "canvas/Persistency/Common/Ptr.h" 
#include "canvas/Persistency/Common/PtrVector.h"
#include "cetlib/maybe_ref.h" 
//#include "art/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"
#include "lardataobj/RecoBase/Track.h"
#include "lardata/Utilities/AssociationUtil.h"
#include <memory>
#include "art_root_io/TFileService.h"
#include "lardataobj/RecoBase/PFParticle.h"
#include "larsim/MCCheater/BackTrackerService.h"
#include "larsim/MCCheater/ParticleInventoryService.h"
#include <TH1.h>
#include <TTree.h>
#include <TLorentzVector.h>
#include "math.h"
#include <limits>

class SignalPionAbsorption;

class SignalPionAbsorption : public art::EDFilter {
public:
  // The destructor generated by the compiler is fine for classes without bare pointers or other resource use.
  // Plugins should not be copied or assigned.

  explicit SignalPionAbsorption(fhicl::ParameterSet const & p);
  SignalPionAbsorption(SignalPionAbsorption const &) = delete;
  SignalPionAbsorption(SignalPionAbsorption &&) = delete;
  SignalPionAbsorption & operator = (SignalPionAbsorption const &) = delete;
  SignalPionAbsorption & operator = (SignalPionAbsorption &&) = delete;
  
  // Required functions
  bool filter(art::Event & e) override; // true to keep event, false to reject
  void beginJob() override;
  void reconfigure(fhicl::ParameterSet const & p);

  // Helpers 
  bool isInReducedVolume(simb::MCParticle *track); 
  int lastPointInTPC(simb::MCParticle *track);
  int firstPointInTPC(simb::MCParticle *track);
  double trackMagnitude(simb::MCParticle *track, unsigned int cut1, unsigned int cut2);
  
private:
  std::string fWCTPCTrkProducerLabel;
  
  // fcl parameters
  bool debug;

  float PROTON_ENERGY_LOWER_BOUND;
  float PROTON_ENERGY_UPPER_BOUND;

  // TTree 
  TTree* fTree; 

  // Variables of interest
  int run;
  int subrun;
  int event;

  int iNumNucleons;
  int iNumProtons;
  int iNumNeutrons;
  bool protonsInFinalState;

  float fPionInitialEnergy;
  float fPionInitialKEnergy;

  float fPionVertexEnergy;
  float fPionVertexKEnergy;

  float fPionVertexMomentum;
  float fPionVertexPx;
  float fPionVertexPy;
  float fPionVertexPz;
  float fPionTrackLength;

  float fLeadingOutMomentum;
  float fTotalOutMomentum;
  float fTotalOutPx;
  float fTotalOutPy;
  float fTotalOutPz;
  float fTotalOutEnergy;
  float fTotalOutKEnergy;

  float fDiffInOutMomentum;
  float fDiffInOutPx;
  float fDiffInOutPy;
  float fDiffInOutPz;
  float fDiffInEnergyOutKEnergy;

  float fCosAngleInOutMomentum;

  // Masses
  const double PionMass    = .13957018;    // in GeV
  const double ProtonMass  = .93827208816; // in GeV
  const double NeutronMass = .9395654133;  // in GeV

  // Detector dimensions
  const double minX =  0.0;
  const double maxX = 47.0;
  const double minY =-20.0; 
  const double maxY = 20.0; 
  const double minZ =  3.0;
  const double maxZ = 87.0;
  
  // Fiducial volume for interactions
  const double RminX =  5.0;
  const double RmaxX = 42.0;
  const double RminY =-15.0; 
  const double RmaxY = 15.0; 
  const double RminZ =  8.0;
  const double RmaxZ = 82.0;
};

SignalPionAbsorption::SignalPionAbsorption(fhicl::ParameterSet const & p) : EDFilter(p)
{  
  this->reconfigure(p);
}

bool SignalPionAbsorption::filter(art::Event & e)
{  
  run    = e.run();
  subrun = e.subRun();
  event  = e.event();

  // Services
  art::ServiceHandle<cheat::ParticleInventoryService> pi_serv;

  // Get particle list
  const sim::ParticleList& plist = pi_serv->ParticleList();

  bool isPrimaryPartPion = false;
  std::vector<int> daughterTrackIDs;

  int nPrimary = 0; // keep track of primary negative pions
  TLorentzVector VPionVertexMomentum;

  // Looping over all the Geant4 particles from the BackTracker
  for (size_t p = 0; p < plist.size(); ++p)
  {
    auto mcPart = plist.Particle(p);
    
    // Check primary particle is negative pion
    if (mcPart->Process() == "primary" && mcPart->PdgCode() == -211) {
      // Check that interaction vertex is in fiducial volume
      if (!isInReducedVolume(mcPart)) continue;
      
      isPrimaryPartPion = true;

      // Get daughters
      for (int i = 0; i < mcPart->NumberDaughters(); ++i) daughterTrackIDs.push_back(mcPart->Daughter(i));

      // Get pion data
      fPionInitialKEnergy = mcPart->E(0) - PionMass; 
      fPionInitialEnergy = mcPart->E(0);
      fPionTrackLength = trackMagnitude(mcPart, firstPointInTPC(mcPart), lastPointInTPC(mcPart));

      int vertexIndex = mcPart->NumberTrajectoryPoints() - 2;
      VPionVertexMomentum = mcPart->Momentum(vertexIndex);

      fPionVertexMomentum = VPionVertexMomentum.P();
      fPionVertexKEnergy = VPionVertexMomentum.E() - PionMass;
      fPionVertexEnergy = VPionVertexMomentum.E();
      fPionVertexPx = VPionVertexMomentum.Px();
      fPionVertexPy = VPionVertexMomentum.Py();
      fPionVertexPz = VPionVertexMomentum.Pz();
      
      nPrimary++; // checking there is a single primary particle
      // break;
    }
  }

  // In case we have more than one primary particle
  if (nPrimary > 1) {
    std::cout << "Num primary negative pions particles: " << nPrimary << std::endl;
    std::cout << run << " " << subrun << " " << event << std::endl;
    return false;
  }

  if (!isPrimaryPartPion) return false;

  int nProtonsPiInelastic = 0;
  int nNeutronsPiInelastic = 0;

  bool bCaptureAtRest = false;

  // Momentum of daughet particles
  TLorentzVector VTotalOutMomentum;
  fLeadingOutMomentum = std::numeric_limits<float>::min();
  fTotalOutKEnergy = 0;
  fTotalOutEnergy = 0;

  // Get daughters
  for (size_t p = 0; p < plist.size(); ++p)
  {
    auto mcPart = plist.Particle(p);

    // Track id of particle matches track id for daughter particles
    if (std::find(daughterTrackIDs.begin(), daughterTrackIDs.end(), mcPart->TrackId()) != daughterTrackIDs.end()) 
    {
      // If daughter is an electron coming from ionization, we do not care
      if ((mcPart->PdgCode() == 11) && (mcPart->Process() == "hIoni")) continue;

      // Reject events with any pion in final state from any process
      if ((mcPart->PdgCode() == 111) || (mcPart->PdgCode() == 211) || (mcPart->PdgCode() == -211)) return false;

      // Reject any decays
      if (mcPart->Process() == "Decay") return false;

      // Count particles coming from inelastic collision 
      if (mcPart->Process() == "pi-Inelastic") {
        // Check daughter is in TPC
        if (lastPointInTPC(mcPart)==9999) continue;

        TLorentzVector VPartMomentum = mcPart->Momentum(0);
        float fPartMomentum = mcPart->P(0);
        fTotalOutEnergy += mcPart->E();

        if (mcPart->PdgCode() == 2112) {
          nNeutronsPiInelastic++;
          VTotalOutMomentum += VPartMomentum;
          if (fPartMomentum > fLeadingOutMomentum) fLeadingOutMomentum = fPartMomentum;
          fTotalOutKEnergy += mcPart->E() - NeutronMass;
        }
        else if (mcPart->PdgCode() == 2212) {
          // Skip invisible protons
          float KEnergy = mcPart->E() - ProtonMass;
          if ((KEnergy < PROTON_ENERGY_LOWER_BOUND) || (KEnergy > PROTON_ENERGY_UPPER_BOUND)) {
            continue;
          }

          nProtonsPiInelastic++;
          VTotalOutMomentum += VPartMomentum;
          if (fPartMomentum > fLeadingOutMomentum) fLeadingOutMomentum = fPartMomentum;
          fTotalOutKEnergy += mcPart->E() - ProtonMass;
        }
        else if ((mcPart->PdgCode() == 13) || (mcPart->PdgCode() == -13)) { return false; } // muon
        else if ((mcPart->PdgCode() == 321) || (mcPart->PdgCode() == -321) || (mcPart->PdgCode() == 311)) { return false; } // kaon
      }

      // Check if pion was captured at rest
      if (mcPart->Process() == "hBertiniCaptureAtRest") {
        bCaptureAtRest = true;
        break;
      }
    }
  }
  // Reject capture at rest
  if (bCaptureAtRest) return false;

  // Set variables of interest
  iNumNucleons = nProtonsPiInelastic + nNeutronsPiInelastic;
  iNumProtons = nProtonsPiInelastic;
  iNumNeutrons = nNeutronsPiInelastic;

  fTotalOutMomentum = VTotalOutMomentum.P();
  fTotalOutPx = VTotalOutMomentum.Px();
  fTotalOutPy = VTotalOutMomentum.Py();
  fTotalOutPz = VTotalOutMomentum.Pz();

  fDiffInOutMomentum = VPionVertexMomentum.P() - fTotalOutMomentum;
  fDiffInOutPx = VPionVertexMomentum.Px() - VTotalOutMomentum.Px();
  fDiffInOutPy = VPionVertexMomentum.Py() - VTotalOutMomentum.Py();
  fDiffInOutPz = VPionVertexMomentum.Pz() - VTotalOutMomentum.Pz();
  fDiffInEnergyOutKEnergy = fPionVertexEnergy - fTotalOutKEnergy;

  fCosAngleInOutMomentum = TMath::Cos(VPionVertexMomentum.Angle(VTotalOutMomentum.Vect()));

  if (iNumProtons > 0) {
    protonsInFinalState = true;
  } else {
    protonsInFinalState = false;
  }
  
  // Populate tree
  fTree->Fill();

  return true;
}

bool SignalPionAbsorption::isInReducedVolume(simb::MCParticle *track) {
  return (
    (track->EndX()>RminX) && (track->EndX()<RmaxX) && 
    (track->EndY()>RminY) && (track->EndY()<RmaxY) && 
    (track->EndZ()>RminZ) && (track->EndZ()<RmaxZ)
  );
}

int SignalPionAbsorption::lastPointInTPC(simb::MCParticle *track)
{
  for (int i=track->NumberTrajectoryPoints()-1; i >=0; i--) {
    if (
      (track->Vx(i)>minX) && (track->Vx(i)<maxX) && 
      (track->Vy(i)>minY) && (track->Vy(i)<maxY) && 
      (track->Vz(i)>minZ) && (track->Vz(i)<maxZ)
    ) return i; // If present in TPC, return last point
  } 
  return 9999;
}

int SignalPionAbsorption::firstPointInTPC(simb::MCParticle *track)
{
  for (unsigned int i=0; i < track->NumberTrajectoryPoints(); ++i) {
    if (
      (track->Vx(i)>minX) && (track->Vx(i)<maxX) && 
      (track->Vy(i)>minY) && (track->Vy(i)<maxY) && 
      (track->Vz(i)>minZ) && (track->Vz(i)<maxZ)
    ) return i; // If present in TPC, return first point
  } 
  return 9999;
}

double SignalPionAbsorption::trackMagnitude(simb::MCParticle *track, unsigned int cut1, unsigned int cut2)
{
  return sqrt(
    pow(track->Vx(cut2)-track->Vx(cut1),2) + 
    pow(track->Vy(cut2)-track->Vy(cut1),2) + 
    pow(track->Vz(cut2)-track->Vz(cut1),2)
  );
}

void SignalPionAbsorption::reconfigure(fhicl::ParameterSet const & p)
{                                                                                                   
  debug = p.get<bool>("debug", false);
  PROTON_ENERGY_LOWER_BOUND = p.get<float>("ProtonEnergyLowerBound", 0.075);
  PROTON_ENERGY_UPPER_BOUND = p.get<float>("ProtonEnergyUpperBound", 1.0);
}

void SignalPionAbsorption::beginJob()
{
  art::ServiceHandle<art::TFileService> tfs;

  // Tree with variables of interest
  fTree = tfs->make<TTree>("PionAbsorptionTree", "Analysis tree");

  fTree->Branch("run", &run, "run/I");
  fTree->Branch("subrun", &subrun, "subrun/I");
  fTree->Branch("event", &event, "event/I");

  fTree->Branch("iNumNucleons", &iNumNucleons, "iNumNucleons/I");
  fTree->Branch("iNumProtons", &iNumProtons, "iNumProtons/I");
  fTree->Branch("iNumNeutrons", &iNumNeutrons, "iNumNeutrons/I");
  fTree->Branch("protonsInFinalState", &protonsInFinalState, "protonsInFinalState/B");

  fTree->Branch("fPionInitialEnergy", &fPionInitialEnergy, "fPionInitialEnergy/F");
  fTree->Branch("fPionInitialKEnergy", &fPionInitialKEnergy, "fPionInitialKEnergy/F");
  fTree->Branch("fPionVertexEnergy", &fPionVertexEnergy, "fPionVertexEnergy/F");
  fTree->Branch("fPionVertexKEnergy", &fPionVertexKEnergy, "fPionVertexKEnergy/F");

  fTree->Branch("fPionVertexMomentum", &fPionVertexMomentum, "fPionVertexMomentum/F");
  fTree->Branch("fPionVertexPx", &fPionVertexPx, "fPionVertexPx/F");
  fTree->Branch("fPionVertexPy", &fPionVertexPy, "fPionVertexPy/F");
  fTree->Branch("fPionVertexPz", &fPionVertexPz, "fPionVertexPz/F");
  fTree->Branch("fPionTrackLength", &fPionTrackLength, "fPionTrackLength/F");

  fTree->Branch("fTotalOutEnergy", &fTotalOutEnergy, "fTotalOutEnergy/F"); 
  fTree->Branch("fTotalOutKEnergy", &fTotalOutKEnergy, "fTotalOutKEnergy/F");

  fTree->Branch("fTotalOutMomentum", &fTotalOutMomentum, "fTotalOutMomentum/F");
  fTree->Branch("fTotalOutPx", &fTotalOutPx, "fTotalOutPx/F");
  fTree->Branch("fTotalOutPy", &fTotalOutPy, "fTotalOutPy/F");
  fTree->Branch("fTotalOutPz", &fTotalOutPz, "fTotalOutPz/F");
  fTree->Branch("fLeadingOutMomentum", &fLeadingOutMomentum, "fLeadingOutMomentum/F");

  fTree->Branch("fDiffInOutMomentum", &fDiffInOutMomentum, "fDiffInOutMomentum/F");
  fTree->Branch("fDiffInOutPx", &fDiffInOutPx, "fDiffInOutPx/F");
  fTree->Branch("fDiffInOutPy", &fDiffInOutPy, "fDiffInOutPy/F");
  fTree->Branch("fDiffInOutPz", &fDiffInOutPz, "fDiffInOutPz/F");
  fTree->Branch("fDiffInEnergyOutKEnergy", &fDiffInEnergyOutKEnergy, "fDiffInEnergyOutKEnergy/F");

  fTree->Branch("fCosAngleInOutMomentum", &fCosAngleInOutMomentum, "fCosAngleInOutMomentum/F");
}

DEFINE_ART_MODULE(SignalPionAbsorption)
